version: "3"
# this file uses prebuilt image in dockerhub
services:
  jekyll:
    image: amirpourmand/al-folio:slim
    build: .
    ports:
      - 8888:8888
      - 35729:35729
    volumes:
      - .:/srv/jekyll
